---
- name: List All Confluence Spaces
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    confluence_base_url: "{{ lookup('env', 'confluence_base_url') }}"
    confluence_api_token: "{{ lookup('env', 'confluence_api_token') }}"
    confluence_email: "{{ lookup('env', 'confluence_email') }}"

  tasks:
    - name: Debug connection information
      debug:
        msg: 
          - "Checking connection to: {{ confluence_base_url }}"
          - "Using email: {{ confluence_email }}"
          - "API token length: {{ confluence_api_token | length }}"

    - name: Get list of all Confluence spaces
      uri:
        url: "{{ confluence_base_url }}rest/api/space"
        method: GET
        user: "{{ confluence_email }}"
        password: "{{ confluence_api_token }}"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Accept: "application/json"
        return_content: yes
      register: spaces_response

    - name: Display spaces information
      debug:
        msg: |
          Verfügbare Spaces:
          {% for space in spaces_response.json.results %}
          - Space Name: {{ space.name }}
            Space-Schlüssel: {{ space.key }}
            Typ: {{ space.type }}
            Status: {{ space.status }}
          {% endfor %}
      when: spaces_response.status == 200
