---
- name: Gather CPU RAM and Disk Space Usage
  hosts: all
  gather_facts: yes
  tasks:
    - name: Gather CPU usage
      command: mpstat 1 1 | awk '/Average/ {print 100 - $12}'
      register: cpu_usage

    - name: Gather RAM Usage
      command: free | awk '/Mem/ {printf "%.2f\n", $3/$2 * 100}'
      register: ram_usage

    - name: Gather Disk Space
      command: df -h --output=pcent / | awk 'NR==2 {print $1}'
      register: disk_space

    - name: Usage Stats
      debug:
        msg: 
          - "Executed On: {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
          - "CPU Usage: {{ cpu_usage.stdout }}%"
          - "RAM Usage: {{ ram_usage.stdout }}%"
          - "Disk Space Used: {{ disk_space.stdout }}"
