---
- hosts: proxmox
  gather_facts: yes
  tasks:
    - name: Create a Proxmox VM from template
      proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: 104
        node: "{{ proxmox_vm_node }}"
        name: 'ubuntu-new'
        clone: 'ubuntu-template'
        cores: 2
        memory: 4096
