---
- name: List All Confluence Spaces
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    confluence_base_url: "https://confluence.mpg.de"
    confluence_api_token: "{{ lookup('env', 'confluence_api_token') }}"

  tasks:
    - name: Debug connection information
      debug:
        msg: 
          - "Checking connection to: {{ confluence_base_url }}/rest/api/space"
          - "API token length: {{ confluence_api_token | length }}"

    - name: Get list of all Confluence spaces
      uri:
        url: "{{ confluence_base_url }}/rest/api/space"
        method: GET
        headers:
          Authorization: "Bearer {{ confluence_api_token }}"
          Accept: "application/json"
        validate_certs: yes
        return_content: yes
        status_code: [200, 401, 403]
      register: spaces_response

    - name: Debug API response on error
      debug:
        msg: 
          - "Status Code: {{ spaces_response.status }}"
          - "URL used: {{ spaces_response.url }}"
          - "Response Headers: {{ spaces_response }}"
      failed_when: spaces_response.status == 401
      when: spaces_response.status != 200

    - name: Display spaces information
      debug:
        msg: |
          Verfügbare Spaces:
          {% for space in spaces_response.json.results %}
          - Space Name: {{ space.name }}
            Space-Schlüssel: {{ space.key }}
            Typ: {{ space.type }}
            Status: {{ space.status }}
          {% endfor %}
      when: spaces_response.status == 200
